import Head from "next/head";
import { Product, FooterBanner, HeroBanner } from "../components";
import { client } from "../lib/client";

export default function Home({ products, bannerData }) {
  console.log(bannerData[0]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeroBanner heroBanner={bannerData[0]} />

        <div className="products-heading">
          <h2>Featured Products</h2>
        </div>

        <div className="products-container">
          {products?.map((product) => (
            <h1>{product.name}</h1>
          ))}
        </div>
      </div>

      <FooterBanner />
    </>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "product"]`;
  const products = await client.fetch(query);

  const bannerQuery = `*[_type == "banner"]`;
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
